version: '3.8'
services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres1234
      - POSTGRES_DB=postgres
      - POSTGRES_USER=super_admin
